services:
  app:
    build: .
    container_name: kuda-finance
    depends_on:
      neo4j:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app_network
    restart: unless-stopped

  neo4j:
    image: neo4j:5.14
    container_name: neo4j_db
    env_file:
      - .env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:7474",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  app_network:
    driver: bridge

volumes:
  neo4j_data:
